variables:
  GCLOUD_PROJECT_ID: 'node-3tier-application'
  APP_NAME: 'web'

stages:
  - lint
  # - build
  # - deploy

lint:
  image: node:alpine
  stage: lint
  script:
    - cd $APP_NAME
    - npm install
    - npm run lint

build:
  image: dwdraju/alpine-gcloud
  stage: build
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/service-account-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/service-account-key.json
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud builds submit $APP_NAME --config=.cloudbuild.yml --substitutions BRANCH_NAME=${CI_COMMIT_SHORT_SHA},_IMAGE_NAME=$APP_NAME
  # only:
  #   - branches

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data "${CERTIFICATE_AUTHORITY_DATA}"
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed "s/PROJECT_ID/$GCLOUD_PROJECT_ID/; s/LATEST/${CI_COMMIT_SHORT_SHA}/" $APP_NAME/deploy/deployment.yml | kubectl apply -f -
    - rm -rf ~/.kube/config
