variables:
  GCLOUD_PROJECT_ID: 'node-3tier-app'
  APP_NAME: 'web'
  IMAGE_NAME: 'api'

stages:
  - build

before_script:
  - mkdir -p $HOME/.docker
  - echo "$DOCKER_AUTH_CONFIG" >> "$HOME/.docker/config.json"


# pullpushtest:
#   image: 'docker:latest'
#   stage: pushpull
#   script:
#     - docker run hello-world
    # - docker pull $REGISTRY_URL/$GCLOUD_PROJECT_ID/$APP_NAME:$CI_COMMIT_SHA
    # - docker push $REGISTRY_URL/$GCLOUD_PROJECT_ID/$APP_NAME:$CI_COMMIT_SHA


build:
  image: dwdraju/alpine-gcloud
  stage: build
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/service-account-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/service-account-key.json
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud builds submit $IMAGE_NAME --config=.cloudbuild.yml --substitutions BRANCH_NAME=$CI_COMMIT_REF_NAME,_IMAGE_NAME=$IMAGE_NAME
  # only:
  #   - branches
